In [1]:
import numpy as np
import pandas as pd

# Part 1 - Numpy
# Problem 1
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1,7]])

In [2]:
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [3]:
mean_a = a.mean(axis = 0)

In [4]:
print(mean_a)

[2.  8.4]


In [5]:
# Problem 2
a_centered = a - mean_a

In [6]:
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [7]:
# Problem 3
print(a[0:])

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [8]:
a_centered_col_0 = a_centered[:, 0]
a_centered_col_1 = a_centered[:, 1]
print(a_centered_col_0)
print(a_centered_col_1)

[-1.  0.  1.  1. -1.]
[-2.4 -0.4  2.6  1.6 -1.4]


In [9]:
a_centered_sp = a_centered_col_0 @ a_centered_col_1
print(a_centered_sp)

8.0


In [10]:
(a_centered_sp)/(len(a[:, 0]) - 1)

2.0

In [11]:
# Problem 4
m = a.T
print(m)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


In [12]:
m_cov = np.cov(m)
print(m_cov)

[[1.  2. ]
 [2.  4.3]]


In [17]:
# Part 2 - Pandas
# Problem 1
authors = pd.DataFrame({
   "author_id": [1, 2, 3],
   "author_name": ['Тургенев', 'Чехов', 'Островский']
})

books = pd.DataFrame({
    "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    "price": [450, 300, 350, 500, 450, 370, 290]
})

authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [18]:
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [19]:
# Problem 2
authors_price = pd.merge(authors, books, on = 'author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [25]:
# Problem 3
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [64]:
# Problem 4
authors_stats = authors_price.groupby("author_name").agg({"price": ['min', 'max', 'mean']})
authors_stats


price                 
              min  max        mean
author_name                       
Островский    290  370  330.000000
Тургенев      300  450  366.666667
Чехов         450  500  475.000000